AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for FastAPI app with EC2, RDS PostgreSQL, and Application Load Balancer

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for FastAPI application

  DBUsername:
    Type: String
    Default: admin
    Description: PostgreSQL Database Username

  DBPassword:
    Type: String
    Description: PostgreSQL Database Password
    NoEcho: true

  DBName:
    Type: String
    Default: fastapidb
    Description: PostgreSQL Database Name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where resources will be created.

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB allowing HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  FastApiInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from ALB and RDS access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref FastApiInstanceSecurityGroup

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow database access only from EC2 instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref FastApiInstanceSecurityGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: FastApiLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - subnet-0d28ac14239b7e7ab
        - subnet-0c16720ab2eafc49f  # Update with your subnets

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FastApiTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  FastApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref FastApiInstanceSecurityGroup
      ImageId: ami-0ddc798b3f1a5117e  # Replace with an updated Amazon Linux AMI
      KeyName: fastapi-key-pair  # Replace with your EC2 KeyPair
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y
            yum install -y python3-pip git
            pip3 install fastapi uvicorn psycopg2-binary

  PostgreSQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
