AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for FastAPI app with EC2, RDS PostgreSQL, and Application Load Balancer

Parameters:
  DBUsername:
    Type: String
    Default: admin
    Description: PostgreSQL Database Username

  DBPassword:
    Type: String
    Description: PostgreSQL Database Password
    NoEcho: true

  DBName:
    Type: String
    Default: fastapidb
    Description: PostgreSQL Database Name

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where resources will be created.

Resources:
  FastApiInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and RDS access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16  # Allow access from VPC CIDR instead of direct SG reference

  FastApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref FastApiInstanceSecurityGroup
      ImageId: ami-0ddc798b3f1a5117e  # Update with a valid AMI
      KeyName: fastapi-key-pair  # Replace with your EC2 KeyPair
      UserData: 
        Fn::Base64: 
          Fn::Sub: |
            #!/bin/bash
            yum update -y
            yum install -y python3-pip git
            pip3 install fastapi uvicorn psycopg2-binary

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow database access within VPC
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16  # Allow access from VPC CIDR

  PostgreSQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: FastApiLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - subnet-0d28ac14239b7e7ab
        - subnet-0c16720ab2eafc49f  # Update with your subnets

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FastApiTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
