version: "3"  

services:

  api:
    image: image_in_repository
    depends_on:
      - postgres  
    ports:
      - "80:8000"  
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000   
    environment:
      # Environment variables for the API application
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} 
      - DATABASE_PORT=${DATABASE_PORT}   
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}   
      - DATABASE_NAME=${DATABASE_NAME}   
      - DATABASE_USERNAME=${DATABASE_USERNAME}   
      - SECRET_KEY=${SECRET_KEY} 
      - ALGORITHM=${ALGORITHM}  
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES} 

  # Service for PostgreSQL
  postgres:
    image: postgres  
    environment:
      # Environment variables for PostgreSQL
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
      - POSTGRES_DB=${DATABASE_NAME}  
    volumes:
      - mount:/var/lib/postgresql/data  

# Volumes section for persisting data
volumes:
  mount:  
